CLUSTAL multiple sequence alignment by MUSCLE (3.8)


TRBJ1-4*01      ----TGCAACTAATGAAAAACTGTTTTTTGGCAGTGGAACCCAGCTCTCTGTCTTGGN
TRBJ1-3*01      AGCTC-----TGGAAACACCATATATTTTGGAGAGGGAAGTTGGCTCACTGTTGTAGN
TRBJ1-2*01      -------AGCTAACTATGGCTACACCTTCGGTTCGGGGACCAGGTTAACCGTTGTAGN
TRBJ1-5*01      ----TATAG-CAATCAGCCCCAGCATTTTGGTGATGGGACTCGACTCTCCATCCTAGN
TRBJ1-1*01      ----CATGAACACTGAAGCTTT---CTTTGGACAAGGCACCAGACTCACAGTTGTAGN
TRBJ1-6*01      AGCTCCTA--TAATTCACCCCTCCACTTTGGGAATGGGACCAGGCTCACTGTGACAGN
TRBJ1-6*02      AGCTCCTA--TAATTCACCCCTCCACTTTGGGAACGGGACCAGGCTCACTGTGACAGN
TRBJ2-3*01      -----CTAG-CACAGATACGCAGTATTTTGGCCCAGGCACCCGGCTGACAGTGCTCGN
TRBJ2-4*01      -----CTAGCCAAAAACATTCAGTACTTCGGCGCCGGGACCCGGCTCTCAGTGCTGGN
TRBJ2-5*01      -----GTA--CCAAGAGACCCAGTACTTCGGGCCAGGCACGCGGCTCCTGGTGCTCGN
TRBJ2-1*01      AGCTCCTA--CAATGAG---CAGTTCTTCGGGCCAGGGACACGGCTCACCGTGCTAGN
TRBJ2-7*01      AGCTCCTA--------CGAGCAGTACTTCGGGCCGGGCACCAGGCTCACGGTCACAGN
TRBJ2-7*02      AGCTCCTA--------CGAGCAGTACGTCGGGCCGGGCACCAGGCTCACGGTCACAGN
TRBJ2-6*01      AGCTCTGG--GGCCAACGTCCTGACTTTCGGGGCCGGCAGCAGGCTGACCGTGCTGGN
TRBJ2-2*01      ----CGCGAACACCGGGGAGCTGTTTTTTGGAGAAGGCTCTAGGCTGACCGTACTGGN
                                           * **    **        *     *    **