CHOICE1_VARIABLE_COLNAMES = ['motif', '5end_base_count', 'weighted_avg_mh']
CHOICE2_VARIABLE_COLNAMES = ['ligation_mh']
VARIABLE_COLNAMES = CHOICE1_VARIABLE_COLNAMES + CHOICE2_VARIABLE_COLNAMES
COUNT_COLNAME = 'weighted_observation'
TWOSTEP=True
