CHOICE1_VARIABLE_COLNAMES = ['5end_base_count', '3end_base_count', 'average_mh']
CHOICE2_VARIABLE_COLNAMES = ['ligation_mh']
VARIABLE_COLNAMES = CHOICE1_VARIABLE_COLNAMES + CHOICE2_VARIABLE_COLNAMES
COUNT_COLNAME = 'weighted_observation'
TWOSTEP=True
