CHOICE1_VARIABLE_COLNAMES = ['motif', '5end_base_count', '3end_base_count', 'average_mh']
CHOICE2_VARIABLE_COLNAMES = []
VARIABLE_COLNAMES = CHOICE1_VARIABLE_COLNAMES + CHOICE2_VARIABLE_COLNAMES
COUNT_COLNAME = 'weighted_observation'
TWOSTEP=True
