TRIM_TYPE = 'v-j_trim_ligation-mh'
PRODUCTIVITY = 'both'
MOTIF_TYPE = 'unbounded'
GENE_NAME = TRIM_TYPE[0:3] + '_gene'
UPPER_TRIM_BOUND = 14
LOWER_TRIM_BOUND = -2
INSERTIONS = 'zero'
MODEL_GROUP = 'all_subjects'
GENE_WEIGHT_TYPE = 'p_gene_pooled'
REPEAT_OBS_COLNAME = None
CHAIN_TYPE = 'TRA'
SAMPLE_ANNOT = False
ONLY_NONPROD_SITES = False
