TRIM_TYPE = 'd3-j_trim'
PRODUCTIVITY = 'nonproductive'
MOTIF_TYPE = 'unbounded'
GENE_NAME = TRIM_TYPE[0:3] + '_gene'
UPPER_TRIM_BOUND = 14
LOWER_TRIM_BOUND = -2
INSERTIONS = 'nonzero'
MODEL_GROUP = 'all_subjects'
GENE_WEIGHT_TYPE = 'p_gene_pooled'
REPEAT_OBS_COLNAME = None
SAMPLE_ANNOT = True
ONLY_NONPROD_SITES = True
